const menuToggle=document.getElementById("menuToggle");const navLinks=document.getElementById("navLinks");menuToggle.addEventListener("click",()=>{navLinks.classList.toggle("active");menuToggle.textContent=navLinks.classList.contains("active")?"✕":"☰"});document.querySelectorAll(".nav-links a").forEach(link=>link.addEventListener("click",()=>{navLinks.classList.remove("active");menuToggle.textContent="☰"}));

const themeToggle=document.getElementById("themeToggle");themeToggle.addEventListener("click",()=>{document.body.classList.toggle("dark");const dark=document.body.classList.contains("dark");themeToggle.textContent=dark?"☀️":"🌙";localStorage.setItem("theme",dark?"dark":"light")});if(localStorage.getItem("theme")==="dark"){document.body.classList.add("dark");themeToggle.textContent="☀️"}

const revealElements=document.querySelectorAll(".reveal");const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("active")})},{threshold:.15});revealElements.forEach(element=>revealObserver.observe(element));

const progressBars=document.querySelectorAll(".progress-bar");const skillObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){const bar=entry.target;bar.style.width=bar.getAttribute("data-width");skillObserver.unobserve(bar)}})},{threshold:.5});progressBars.forEach(bar=>skillObserver.observe(bar));

const contactForm=document.getElementById("contactForm");const formMessage=document.getElementById("formMessage");contactForm.addEventListener("submit",event=>{event.preventDefault();const name=document.getElementById("name"),email=document.getElementById("email"),message=document.getElementById("message");let valid=true;document.querySelectorAll(".error").forEach(error=>error.textContent="");formMessage.textContent="";if(name.value.trim()===""){name.nextElementSibling.textContent="Please enter your name.";valid=false}const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(email.value.trim()===""){email.nextElementSibling.textContent="Please enter your email.";valid=false}else if(!emailPattern.test(email.value.trim())){email.nextElementSibling.textContent="Please enter a valid email.";valid=false}if(message.value.trim()===""){message.nextElementSibling.textContent="Please enter your message.";valid=false}else if(message.value.trim().length<10){message.nextElementSibling.textContent="Message must be at least 10 characters.";valid=false}if(valid){formMessage.textContent="Message validated successfully!";formMessage.style.color="#16a34a";contactForm.reset()}});

const sections=document.querySelectorAll("section[id]"),navItems=document.querySelectorAll(".nav-links a");window.addEventListener("scroll",()=>{let current="";sections.forEach(section=>{if(window.scrollY>=section.offsetTop-150)current=section.getAttribute("id")});navItems.forEach(link=>{link.style.color="";if(link.getAttribute("href")===`#${current}`)link.style.color="var(--primary)"})});